"use client";
import { useEffect,useMemo,useState } from "react";
import { CalendarClock,ExternalLink,Mail,Pause,Play,Save,Sparkles } from "lucide-react";
type Row=Record<string,unknown>;type Lead=Row&{id:string;workspaceId?:string;company:string;email?:string;contacts?:Row[];evidence?:Row[];messages?:Row[];drafts?:Row[];sequences?:Row[]};
type Account={id:string;email_address:string;display_name?:string;status:string;workspaces:Array<{id:string;name:string}>};
type Step={id?:string;step_order:number;delay_days:number;scheduled_at?:string;subject:string;body:string;status:string;gmail_draft_id?:string;version?:number};
const actions=[['icebreaker','Générer l’icebreaker'],['subject','Améliorer l’objet'],['shorten','Raccourcir'],['personalize','Rendre plus personnel'],['proof','Ajouter une preuve/chiffre vérifié'],['cta','Optimiser l’appel à l’action'],['regenerate','Régénérer tout l’email']];
export default function LeadEmailCrm({lead}:{lead:Lead}){const[accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(""),[recipient,setRecipient]=useState(String(lead.email||lead.contacts?.find(c=>c.email)?.email||"")),[subject,setSubject]=useState(""),[icebreaker,setIcebreaker]=useState(""),[body,setBody]=useState(""),[signature,setSignature]=useState("Bien à vous,"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[sourceList,setSourceList]=useState<string[]>([]),[sequenceId,setSequenceId]=useState<string|undefined>(),[sequenceStatus,setSequenceStatus]=useState("draft"),[steps,setSteps]=useState<Step[]>(defaultSteps());
  const workspaceId=String(lead.workspaceId||"");const account=accounts.find(a=>a.id===accountId);const facts=useMemo(()=>[...(lead.evidence||[])].slice(0,6).map(e=>String(e.fact||e.category||e.provider||"")).filter(Boolean),[lead.evidence]);
  useEffect(()=>{fetch('/api/email/connections').then(r=>r.json()).then(p=>{const allowed=(p.items||[]).filter((a:Account)=>a.status==='connected'&&a.workspaces?.some(w=>w.id===workspaceId));setAccounts(allowed);setAccountId(allowed[0]?.id||'');}).catch(()=>setNotice('Comptes expéditeurs indisponibles.'));const seq=(lead.sequences||[])[0];if(seq){setSequenceId(String(seq.id));setSequenceStatus(String(seq.status));const saved=(seq.email_sequence_steps||[]) as Step[];if(saved.length===3)setSteps(saved.sort((a,b)=>a.step_order-b.step_order));}},[lead.sequences,workspaceId]);
  async function ai(action:string){setBusy(true);setNotice('');try{const r=await fetch('/api/email/draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,company:lead.company,person:lead.contacts?.[0]?.full_name,offer:(lead.workspace as Row|undefined)?.slug||'Lexicon',evidence:facts.join(' · '),subject,body:[icebreaker,body].filter(Boolean).join('\n\n')})});const p=await r.json();if(!r.ok)throw new Error(p.error);setSubject(p.subject);const paragraphs=String(p.body||'').split(/\n\n+/);setIcebreaker(paragraphs.shift()||'');setBody(paragraphs.join('\n\n'));setSourceList(p.sources||[]);setNotice('Proposition générée à partir des seules preuves affichées.');}catch(e){setNotice(e instanceof Error?e.message:'Génération impossible.');}finally{setBusy(false);}}
  async function saveLocal(){return post('/api/email/local-draft',{accountId,workspaceId,leadId:lead.id,to:recipient,subject,icebreaker,body,signature,sources:sourceList},'Brouillon sauvegardé dans le CRM.');}
  async function createGmailDraft(step?:Step){const payload=step?{subject:step.subject,body:step.body,icebreaker:'',signature}:{subject,body,icebreaker,signature};return post('/api/email/gmail-draft',{accountId,workspaceId,leadId:lead.id,to:recipient,...payload},'Brouillon Gmail réel créé. Aucun email envoyé.');}
  async function post(url:string,payload:Record<string,unknown>,success:string){setBusy(true);setNotice('');try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok)throw new Error(p.error);setNotice(success);return p;}catch(e){setNotice(e instanceof Error?e.message:'Action impossible.');return null;}finally{setBusy(false);}}
  async function saveSequence(){if(!sequenceId){const p=await post('/api/email/sequences',{workspaceId,leadId:lead.id,accountId,name:`Séquence · ${lead.company}`,senderEmail:account?.email_address,steps:steps.map(s=>({delayDays:s.delay_days,subject:s.subject,body:s.body}))},'Séquence de trois emails créée en mode brouillons sûrs.');if(p)setSequenceId(p.id);}else{await patchSequence({steps:steps.map(s=>({id:s.id,delayDays:s.delay_days,scheduledAt:s.scheduled_at,subject:s.subject,body:s.body,status:s.status}))});}}
  async function patchSequence(payload:Record<string,unknown>){if(!sequenceId)return;setBusy(true);const r=await fetch(`/api/email/sequences/${sequenceId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const p=await r.json();setNotice(r.ok?'Séquence mise à jour.':p.error||'Mise à jour impossible.');if(payload.status)setSequenceStatus(String(payload.status));setBusy(false);}
  function change(index:number,patch:Partial<Step>){setSteps(current=>current.map((step,i)=>i===index?{...step,...patch}:step));}
  return <div className="lead-email-crm"><div className="lead-email-editor"><div className="email-editor-head"><div><h3>Éditeur de brouillon personnalisé</h3><p>SAFE_DRAFT_ONLY actif · aucune méthode d’envoi n’est utilisée.</p></div><Mail size={20}/></div><div className="email-editor-grid"><label>Compte expéditeur<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Sélectionner</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.display_name||a.email_address} · {a.email_address}</option>)}</select></label><label>Destinataire<input value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><label className="full">Objet<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="full">Icebreaker<textarea value={icebreaker} onChange={e=>setIcebreaker(e.target.value)}/></label><label className="full">Corps<textarea value={body} onChange={e=>setBody(e.target.value)}/></label><label className="full">Signature<textarea value={signature} onChange={e=>setSignature(e.target.value)}/></label></div><div className="ai-actions">{actions.map(([key,label])=><button key={key} disabled={busy} onClick={()=>void ai(key)}><Sparkles size={12}/>{label}</button>)}</div><aside className="email-preview"><strong>Aperçu final</strong><h4>{subject||'(objet)'}</h4><p>{[icebreaker,body,signature].filter(Boolean).join('\n\n')}</p>{sourceList.length>0&&<small>Sources utilisées : {sourceList.join(' · ')}</small>}</aside><div className="editor-actions"><button onClick={()=>void saveLocal()} disabled={!accountId||busy}><Save size={14}/>Sauvegarder localement</button><button className="primary" onClick={()=>void createGmailDraft()} disabled={!accountId||!recipient||!subject||!body||busy}><Mail size={14}/>Créer un vrai brouillon Gmail</button><a href={`https://mail.google.com/mail/u/${encodeURIComponent(account?.email_address||'')}/#drafts`} target="_blank" rel="noreferrer">Ouvrir Gmail <ExternalLink size={13}/></a></div>{notice&&<p className="composer-notice" role="status">{notice}</p>}</div>
  <section className="lead-sequence"><header><div><h3>Séquence individuelle · 3 emails</h3><p>Chaque étape reste un brouillon jusqu’à validation explicite.</p></div><span>{sequenceStatus}</span></header>{steps.map((step,index)=><article key={step.id||index}><div className="sequence-step-head"><strong>Email {index+1}</strong><select value={step.status} onChange={e=>change(index,{status:e.target.value})}><option>draft</option><option>scheduled</option><option>skipped</option><option>cancelled</option></select><label>Délai <input type="number" min="0" value={step.delay_days} onChange={e=>change(index,{delay_days:Number(e.target.value)})}/> jours</label><label>Date <input type="datetime-local" value={step.scheduled_at?.slice(0,16)||''} onChange={e=>change(index,{scheduled_at:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label><small>v{step.version||1}</small></div><input value={step.subject} onChange={e=>change(index,{subject:e.target.value})} placeholder="Objet"/><textarea value={step.body} onChange={e=>change(index,{body:e.target.value})} placeholder="Corps de l’email"/><button onClick={()=>void createGmailDraft(step)} disabled={!sequenceId||busy}>Créer le brouillon Gmail de cette étape</button></article>)}<footer><button onClick={()=>void saveSequence()} disabled={busy}><Save size={14}/>{sequenceId?'Enregistrer les versions':'Créer la séquence'}</button><button onClick={()=>void patchSequence({status:sequenceStatus==='paused'?'active':'paused'})} disabled={!sequenceId||busy}>{sequenceStatus==='paused'?<Play size={14}/>:<Pause size={14}/>} {sequenceStatus==='paused'?'Reprendre':'Pause'}</button><button onClick={()=>void patchSequence({status:'cancelled',stopReason:'cancelled_by_user'})} disabled={!sequenceId||busy}>Annuler</button><span><CalendarClock size={14}/> Planification sûre, sans envoi</span></footer></section>
  <section className="real-email-history"><h3>Conversation réelle, brouillons et réponses</h3>{(lead.messages||[]).map(message=><article key={String(message.id)}><span>{String(message.direction)}</span><div><strong>{String(message.subject||'(sans objet)')}</strong><p>{String(message.text_body||message.snippet||'')}</p><small>{new Date(String(message.sent_at||message.collected_at)).toLocaleString('fr-BE')} · {String(message.classification||'non classé')}</small></div></article>)}{!(lead.messages||[]).length&&<p>Aucun email synchronisé pour ce lead.</p>}</section></div>;
}
function defaultSteps():Step[]{return[{step_order:1,delay_days:0,subject:'',body:'',status:'draft'},{step_order:2,delay_days:3,subject:'Re: prise de contact',body:'Bonjour,\n\nJe me permets une relance courte avec un autre angle. Répondez simplement « oui » si un échange de 20 minutes maximum peut être utile.',status:'draft'},{step_order:3,delay_days:5,subject:'Dernier message',body:'Bonjour,\n\nJe ne souhaite pas encombrer votre boîte. Si le sujet mérite un court échange, répondez simplement « oui » ; sinon je clôture ici.',status:'draft'}];}
