"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, CalendarClock, ChevronRight, CircleDollarSign, Flame, MapPin, RefreshCw, Search, Target, Trophy, WandSparkles } from "lucide-react";
import { displayText, safeInitial } from "@/lib/provider-normalization";
import ManualLeadDialog from "@/components/manual-lead-dialog";

type Lead = { id:string; company:string; category?:string|null; location?:string|null; city?:string|null; region?:string|null; country?:string|null; email?:string|null; phone?:string|null; linkedinUrl?:string|null; score:number; priorityScore:number; temperature?:string|null; pipelineStage?:string|null; dealStatus?:string|null; opportunityValue?:number; nextAction?:string|null; nextActionAt?:string|null; workspace?:{slug:string;label:string} };
type Payload = { items:Lead[]; page:number; pageCount:number; total:number; counts:Record<string,number>; pipelineValue:number };
const workspaces = [["","Tous autorisés"],["lexicon","Lexicon"],["pluq","Pluq"],["profitflow","Profitflow"],["net-ai","Net.AI / Exploration"]];
const views = [["","Tous"],["non_contacte","Non contactés"],["enrichment:pending","À enrichir"],["froid","Froids"],["tiede","Tièdes"],["chaud","Chauds"],["contacted","Contactés"],["replied","En discussion"],["negotiation","En négociation"],["meeting","Rendez-vous"],["won","Gagnés"],["lost","Perdus"],["overdue","À relancer"]];
const fields = [["campaign","Campagne / recherche"],["status","Statut"],["temperature","Température"],["scoreMin","Score minimum"],["country","Pays"],["region","Région"],["city","Ville"],["sector","Secteur"],["category","Catégorie"],["owner","Responsable"],["createdFrom","Créé après"],["lastInteractionFrom","Interaction après"],["nextActionBefore","Action avant"]] as const;

export default function LeadsCommand({lexiconOnly=false}:{lexiconOnly?:boolean}) {
  const router=useRouter(), pathname=usePathname(), searchParams=useSearchParams(); const paramsKey=searchParams.toString();
  const [payload,setPayload]=useState<Payload>({items:[],page:1,pageCount:1,total:0,counts:{},pipelineValue:0}); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [showFilters,setShowFilters]=useState(false);
  const update=useCallback((patch:Record<string,string|null>)=>{const next=new URLSearchParams(paramsKey);Object.entries(patch).forEach(([key,value])=>value?next.set(key,value):next.delete(key));if(!("page" in patch))next.delete("page");router.push(`${pathname}${next.size?`?${next}`:""}`);},[paramsKey,pathname,router]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/leads?${paramsKey}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Leads indisponibles.");setPayload(data);}catch(cause){setError(cause instanceof Error?cause.message:"Leads indisponibles.");}finally{setLoading(false);}},[paramsKey]);
  useEffect(()=>{void load();},[load]);
  const activeView=useMemo(()=>searchParams.get("nextAction")==="overdue"?"overdue":searchParams.get("enrichment")==="pending"?"enrichment:pending":searchParams.get("status")||searchParams.get("temperature")||"",[searchParams]);
  function selectView(value:string){if(value==="overdue")update({nextAction:"overdue",enrichment:null,status:null,temperature:null});else if(value.startsWith("enrichment:"))update({enrichment:"pending",nextAction:null,status:null,temperature:null});else if(["non_contacte","froid","tiede","chaud"].includes(value))update({temperature:value||null,status:null,enrichment:null,nextAction:null});else update({status:value||null,temperature:null,enrichment:null,nextAction:null});}
  function submitSearch(event:FormEvent<HTMLFormElement>){event.preventDefault();update({q:String(new FormData(event.currentTarget).get("q")||"").trim()||null});}
  const kpis=[
    ["Total",payload.total,"/leads",Target],["Chauds",payload.counts.hot||0,"/leads?temperature=chaud",Flame],["À enrichir",payload.counts.pending||0,"/leads?enrichment=pending",WandSparkles],["À relancer",payload.counts.overdue||0,"/leads?nextAction=overdue",CalendarClock],
    ["Rendez-vous",payload.counts.meeting||0,"/leads?status=meeting",Building2],["En négociation",payload.counts.negotiation||0,"/leads?status=negotiation",CircleDollarSign],["Gagnés",payload.counts.won||0,"/leads?status=won",Trophy],["Valeur pipeline",euro(payload.pipelineValue),"/leads?sort=priority",CircleDollarSign],
  ] as const;
  return <section className="leads-command" aria-busy={loading}>
    <div className="leads-command-actions"><ManualLeadDialog lexiconOnly={lexiconOnly}/></div>
    <nav className="workspace-tabs" aria-label="Espaces de travail">{workspaces.filter(([value])=>!lexiconOnly||value==="lexicon").map(([value,label])=><button key={value||"all"} className={(searchParams.get("workspace")||(lexiconOnly?"lexicon":""))===value?"active":""} onClick={()=>update({workspace:value||null})}>{label}<span>{value?payload.counts[`workspace_${value}`]||0:payload.counts.authorized||payload.total}</span></button>)}</nav>
    <div className="lead-kpis">{kpis.map(([label,value,href,Icon])=><Link key={label} href={href}><Icon size={18}/><span>{label}</span><strong>{value}</strong><ChevronRight size={15}/></Link>)}</div>
    <div className="lead-view-tabs" role="tablist">{views.map(([value,label])=><button role="tab" aria-selected={activeView===value} className={activeView===value?"active":""} key={value||"all"} onClick={()=>selectView(value)}>{label}</button>)}</div>
    <form className="lead-filter-bar" onSubmit={submitSearch}><label><Search size={15}/><input name="q" defaultValue={searchParams.get("q")||""} placeholder="Entreprise, personne, email, ville…"/></label><button type="submit">Rechercher</button><button type="button" onClick={()=>setShowFilters(value=>!value)}>{showFilters?"Masquer":"Tous les filtres"}</button><select aria-label="Trier" value={searchParams.get("sort")||"score"} onChange={event=>update({sort:event.target.value})}><option value="score">Score</option><option value="priority">Priorité</option><option value="created">Ajout</option><option value="interaction">Interaction</option><option value="nextAction">Prochaine action</option><option value="company">Entreprise</option></select><button type="button" className="reset" onClick={()=>router.push(pathname)}><RefreshCw size={14}/>Réinitialiser</button></form>
    {showFilters&&<div className="advanced-filters">{fields.map(([key,label])=><label key={key}>{label}<input type={key.includes("From")||key.includes("Before")?"date":key==="scoreMin"?"number":"text"} min={key==="scoreMin"?0:undefined} max={key==="scoreMin"?100:undefined} value={searchParams.get(key)||""} onChange={event=>update({[key]:event.target.value||null})}/></label>)}{[["hasEmail","Email"],["hasPhone","Téléphone"],["hasLinkedin","LinkedIn"],["hasPhoto","Photo"]].map(([key,label])=><label key={key}>{label}<select value={searchParams.get(key)||""} onChange={event=>update({[key]:event.target.value||null})}><option value="">Tous</option><option value="true">Présent</option><option value="false">Absent</option></select></label>)}</div>}
    {error&&<p className="search-error">{error}</p>}
    <div className="table-card lead-results"><div className="table-scroll"><table><thead><tr><th>Entreprise</th><th>Workspace</th><th>Coordonnées</th><th>Score</th><th>Température</th><th>Statut</th><th>Prochaine action</th><th/></tr></thead><tbody>{payload.items.filter(lead=>lead&&typeof lead.id==="string").map(lead=><tr key={lead.id}><td><Link className="company-cell" href={`/leads/${encodeURIComponent(lead.id)}`}><span className="company-logo">{safeInitial(lead.company)}</span><span><strong>{displayText(lead.company,"Entreprise sans nom")}</strong><small><MapPin size={11}/>{[lead.city,lead.region,lead.country].filter(Boolean).join(" · ")||lead.location||lead.category||"Localisation à enrichir"}</small></span></Link></td><td><span className={`workspace-pill workspace-${lead.workspace?.slug||"net-ai"}`}>{lead.workspace?.label||"Net.AI"}</span></td><td><strong>{lead.email||lead.phone||"À enrichir"}</strong><small>{lead.linkedinUrl?"LinkedIn public":"LinkedIn à confirmer"}</small></td><td><strong>{Number(lead.score||0)}/100</strong><small>Priorité {Number(lead.priorityScore||0)}</small></td><td><span className={`lead-temperature ${lead.temperature||"non_contacte"}`}>{temperatureLabel(lead.temperature)}</span></td><td>{stageLabel(lead.pipelineStage||lead.dealStatus)}</td><td><strong>{lead.nextAction||"À définir"}</strong><small>{lead.nextActionAt?new Date(lead.nextActionAt).toLocaleString("fr-BE"):"Aucune date"}</small></td><td><Link aria-label={`Ouvrir ${displayText(lead.company,"lead")}`} href={`/leads/${encodeURIComponent(lead.id)}`}><ChevronRight size={18}/></Link></td></tr>)}</tbody></table>{!loading&&!payload.items.length&&<div className="empty-results"><Target size={24}/><strong>Aucun lead ne correspond à ces filtres</strong><span>Réinitialisez un filtre ou lancez une recherche depuis le Radar.</span></div>}</div></div>
    <div className="table-footer"><span>{payload.total} lead(s)</span><div className="lead-pagination"><button disabled={payload.page<=1} onClick={()=>update({page:String(payload.page-1)})}>Précédent</button><span>Page {payload.page}/{payload.pageCount}</span><button disabled={payload.page>=payload.pageCount} onClick={()=>update({page:String(payload.page+1)})}>Suivant</button></div><span>{loading?"Actualisation…":"Filtres conservés dans l’URL"}</span></div>
  </section>;
}
function euro(value:number){return new Intl.NumberFormat("fr-BE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(value||0);}
function temperatureLabel(value?:string|null){return ({chaud:"Chaud",tiede:"Tiède",froid:"Froid",non_contacte:"Non contacté"} as Record<string,string>)[value||""]||"Non contacté";}
function stageLabel(value?:string|null){return ({new:"Nouveau",to_qualify:"À qualifier",qualified:"Qualifié",contacted:"Contacté",replied:"En discussion",meeting:"Rendez-vous",negotiation:"Négociation",won:"Gagné",lost:"Perdu",blocked:"Bloqué"} as Record<string,string>)[value||""]||"Nouveau";}
