"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CheckCircle2, ExternalLink, Link2, Mail, MapPin, Phone, RefreshCw, ShieldCheck, UserRound, WandSparkles } from "lucide-react";
import LeadEmailEditorDurable from "@/components/lead-email-editor-durable";
type Row=Record<string,unknown>; type Lead=Row&{id:string;externalId?:string;workspaceId?:string;company:string;contacts?:Row[];evidence?:Row[];sources?:Row[];activities?:Row[];messages?:Row[];drafts?:Row[];sequences?:Row[];tasks?:Row[];enrichmentJobs?:Row[];scoreBreakdown?:Row;workspace?:{slug:string;label:string};searchRun?:Row|null};
const labels:Record<string,string>={queued:"En file",running:"En cours",completed:"Terminé",failed:"Échec",cancelled:"Annulé",partial:"Partiel"};
export default function LeadDetailRich({id}:{id:string}){const[lead,setLead]=useState<Lead|null>(null),[error,setError]=useState(""),[job,setJob]=useState<Row|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch(`/api/leads/${encodeURIComponent(id)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Lead introuvable.");setLead(payload.item);const jobs=(payload.item.enrichmentJobs||[]) as Row[];const active=jobs.find((item:Row)=>["queued","running"].includes(String(item.status)));setJob(active||jobs[0]||null);},[id]);
  useEffect(()=>{void load().catch(cause=>setError(cause instanceof Error?cause.message:"Lead introuvable."));},[load]);
  useEffect(()=>{if(!job||!["queued","running"].includes(String(job.status)))return;const timer=window.setInterval(async()=>{const response=await fetch(`/api/enrich/${encodeURIComponent(String(job.id))}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)return;setJob(payload.job);if(["completed","failed","cancelled"].includes(payload.job.status)){window.clearInterval(timer);if(payload.job.status==="completed"){setNotice("Enrichissement terminé : la fiche a été actualisée.");await load();}}},1200);return()=>window.clearInterval(timer);},[job?.id,job?.status,load]);
  async function enrich(retry=false){if(!lead||busy)return;setBusy(true);setError("");setNotice("");try{if(retry&&job?.id){const response=await fetch(`/api/enrich/${encodeURIComponent(String(job.id))}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"retry"})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Retry impossible.");setJob({...job,status:"queued",progress:0,error_message:null});}else{const response=await fetch("/api/enrich",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:lead.externalId||lead.id,company:lead.company,location:lead.address,sourceUrl:lead.googleMapsUrl,website:lead.website,linkedinUrl:lead.linkedinUrl,maxCostUsd:1,maxContacts:1})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Enrichissement impossible.");setJob({id:payload.jobId,status:"queued",progress:0});}setNotice("Job créé : vous pouvez quitter cette page, le traitement continue côté serveur.");}catch(cause){setError(cause instanceof Error?cause.message:"Enrichissement impossible.");}finally{setBusy(false);}}
  const primary=lead?.contacts?.[0], coords=lead&&Number.isFinite(Number(lead.latitude))&&Number.isFinite(Number(lead.longitude))?[Number(lead.latitude),Number(lead.longitude)]:null;const mapUrl=coords?`https://www.google.com/maps?q=${coords[0]},${coords[1]}&z=16&output=embed`:null;const score=lead?.scoreBreakdown||{};
  const changes=useMemo(()=>job?.result&&typeof job.result==="object"?Object.entries(job.result as Row).filter(([,value])=>value!=null).slice(0,8):[],[job]);
  if(error&&!lead)return <main className="lead-detail-shell"><p className="search-error">{error}</p><Link href="/leads">Retour aux leads</Link></main>;if(!lead)return <main className="lead-detail-shell">Chargement de la fiche…</main>;
  return <main className="lead-detail-shell"><Link className="back-link" href="/leads">← Retour aux leads</Link><header className="lead-hero"><Avatar contact={primary}/><div className="lead-identity"><span className="workspace-pill">{lead.workspace?.label}</span><h1>{primary?.full_name?String(primary.full_name):lead.company}</h1><p>{primary?.title?`${String(primary.title)} · `:""}{lead.company}</p><div className="contact-links">{Boolean(lead.email)&&<a href={`mailto:${String(lead.email)}`}><Mail size={15}/>{String(lead.email)}</a>}{Boolean(lead.phone)&&<a href={`tel:${String(lead.phone).replaceAll(" ","")}`}><Phone size={15}/>{String(lead.phone)}</a>}{Boolean(primary?.linkedin_url||lead.linkedinUrl)&&<a href={String(primary?.linkedin_url||lead.linkedinUrl)} target="_blank" rel="noreferrer"><Link2 size={15}/>LinkedIn</a>}</div></div><div className="lead-head-stats"><span>{temperature(String(lead.temperature||""))}</span><span>{stage(String(lead.pipelineStage||""))}</span><strong>{String(lead.score||0)}/100</strong><small>Prochaine action : {String(lead.nextAction||"à définir")}</small><small>Dernière interaction : {date(lead.lastInteractionAt)}</small></div></header>
  <section className="enrichment-job"><div><WandSparkles size={20}/><div><strong>Enrichissement entreprise + décideur</strong><span>{job?`${labels[String(job.status)]||String(job.status)} · ${Number(job.progress||0)} %`:"Aucun job actif"}</span></div></div><progress max="100" value={Number(job?.progress||0)}/><button onClick={()=>void enrich(false)} disabled={busy||["queued","running"].includes(String(job?.status))}>{busy?"Lancement…":"Rechercher plus d’informations"}</button>{job?.status==="failed"&&<button className="retry" onClick={()=>void enrich(true)}><RefreshCw size={14}/>Réessayer</button>}{Boolean(job?.error_message)&&<p className="search-error">{String(job?.error_message)}</p>}{notice&&<p role="status">{notice}</p>}{changes.length>0&&<div className="new-data"><strong>Nouveautés</strong>{changes.map(([key])=><span key={key}><CheckCircle2 size={13}/>{key}</span>)}</div>}</section>
  <nav className="detail-nav">{["Vue d’ensemble","Décideurs","Entreprise","Google Business et carte","Coordonnées","Analyse et score","Sources et preuves","Historique","Emails et campagnes"].map(item=><a key={item} href={`#${slug(item)}`}>{item}</a>)}</nav>
  <Detail id="vue-densemble" title="Vue d’ensemble"><p>{String(lead.description||"Description publique à enrichir.")}</p><Fact label="Activité" value={lead.activity}/><Fact label="Secteur" value={lead.sector}/><Fact label="Catégorie" value={lead.category}/><Fact label="Créée / ancienneté" value={lead.foundedYear}/><Fact label="Taille" value={lead.companySize||lead.employeeCount}/></Detail>
  <Detail id="decideurs" title="Décideurs"><div className="contact-grid">{lead.contacts?.map(contact=><article key={String(contact.id)}><Avatar contact={contact}/><h3>{String(contact.full_name)}</h3><p>{String(contact.title||"Fonction à confirmer")}</p><small>{String(contact.department||"")} {Boolean(contact.seniority)?`· ${String(contact.seniority)}`:""}</small><Fact label="Email pro" value={contact.email}/><Fact label="Téléphone" value={contact.phone}/><Fact label="Localisation" value={contact.location}/><Fact label="Confiance" value={`${String(contact.confidence_score||0)}/100`}/>{Boolean(contact.linkedin_url)&&<a href={String(contact.linkedin_url)} target="_blank" rel="noreferrer">Ouvrir LinkedIn <ExternalLink size={13}/></a>}</article>)}{!lead.contacts?.length&&<p>Aucun décideur public fiable trouvé. Aucun contact n’a été inventé.</p>}</div></Detail>
  <Detail id="entreprise" title="Entreprise"><div className="detail-grid"><Fact label="Nom officiel" value={lead.legalName||lead.company}/><Fact label="Site" value={lead.website}/><Fact label="Domaine" value={lead.domain}/><Fact label="Employés" value={lead.employeeCount}/><Fact label="Réseaux sociaux" value={format(lead.socialLinks)}/><Fact label="Dernier enrichissement" value={date(lead.lastEnrichedAt)}/></div></Detail>
  <Detail id="google-business-et-carte" title="Google Business et localisation"><div className="map-detail">{mapUrl?<iframe title={`Carte Google de ${lead.company}`} src={mapUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>:<div className="map-unavailable"><MapPin size={24}/>Coordonnées exactes à enrichir</div>}<div><Fact label="Adresse" value={lead.address}/><Fact label="Place ID" value={lead.googlePlaceId}/><Fact label="Coordonnées" value={coords?`${coords[0]}, ${coords[1]}`:null}/><Fact label="Note / avis" value={lead.rating?`${String(lead.rating)}/5 · ${String(lead.reviewCount||0)} avis`:null}/><Fact label="Horaires" value={format(lead.openingHours)}/>{Boolean(lead.photoUrl)&&<img className="business-photo" src={String(lead.photoUrl)} alt={`Établissement ${lead.company}`}/>} {Boolean(lead.googleMapsUrl||coords)&&<a className="primary-cta" href={String(lead.googleMapsUrl||`https://www.google.com/maps?q=${coords?.join(",")}`)} target="_blank" rel="noreferrer">Ouvrir dans Google Maps <ExternalLink size={14}/></a>}<small>Carte et données cartographiques © Google — attribution Google affichée dans la carte.</small></div></div></Detail>
  <Detail id="avis-google" title="Avis Google — lecture limitée"><ReviewPanel leadId={lead.id}/></Detail>
  <Detail id="coordonnees" title="Coordonnées"><div className="detail-grid"><Fact label="Email" value={lead.email}/><Fact label="Téléphone" value={lead.phone}/><Fact label="Adresse" value={lead.address}/><Fact label="Ville" value={lead.city}/><Fact label="Région" value={lead.region}/><Fact label="Pays" value={lead.country}/></div></Detail>
  <Detail id="analyse-et-score" title="Analyse et score"><div className="score-explained"><strong>{String(lead.score||0)}/100</strong><span>Modèle {String(lead.scoreModelVersion||"v1")} · confiance {String(lead.confidence||0)}%</span><Fact label="Facteurs positifs" value={format(score.positive||score.positives)}/><Fact label="Facteurs négatifs" value={format(score.negative||score.negatives)}/><Fact label="Données manquantes" value={format(score.missing)}/><Fact label="Signaux de besoin" value={format(score.signals)}/><Fact label="Adéquation Lexicon / Pluq / Profitflow" value={format(score.fit||score)}/><Fact label="Date des preuves" value={date(lead.updatedAt)}/></div></Detail>
  <Detail id="sources-et-preuves" title="Sources et preuves"><Evidence rows={[...(lead.evidence||[]),...(lead.sources||[])]}/>{Boolean(lead.searchRun)&&<Link href={`/leads?campaign=${encodeURIComponent(String(lead.searchRun?.id))}`}>Ouvrir les leads de la recherche source</Link>}</Detail>
  <Detail id="historique" title="Historique"><Timeline rows={lead.activities||[]}/></Detail><Detail id="emails-et-campagnes" title="Emails et campagnes"><LeadEmailEditorDurable lead={lead}/><Timeline rows={lead.messages||[]}/></Detail>
  </main>;
}
function Detail({id,title,children}:{id:string;title:string;children:React.ReactNode}){return <section id={id} className="lead-detail-section"><h2>{title}</h2>{children}</section>}function Fact({label,value}:{label:string;value:unknown}){return <div className="detail-fact"><span>{label}</span><strong>{value==null||value===""?"À enrichir":String(value)}</strong></div>;}function Avatar({contact}:{contact?:Row}){const name=String(contact?.full_name||"?");return Boolean(contact?.profile_photo_url)?<img className="decision-avatar" src={String(contact?.profile_photo_url)} alt={name}/>:<div className="decision-avatar fallback"><UserRound size={22}/><span>{initials(name)}</span><small>Photo non publique</small></div>;}function Evidence({rows}:{rows:Row[]}){return <div className="evidence-list">{rows.map((row,index)=><article key={String(row.id||index)}><ShieldCheck size={17}/><div><strong>{String(row.fact||row.provider||row.category||"Source publique")}</strong><small>{String(row.confidence||"à vérifier")} · {date(row.collected_at)}</small>{Boolean(row.source_url)&&<a href={String(row.source_url)} target="_blank" rel="noreferrer">Voir la preuve</a>}</div></article>)}{!rows.length&&<p>Aucune preuve collectée.</p>}</div>}function Timeline({rows}:{rows:Row[]}){return <div className="timeline">{rows.map((row,index)=><article key={String(row.id||index)}><CalendarClock size={15}/><div><strong>{String(row.activity_type||row.subject||row.classification||"Événement")}</strong><p>{String(row.notes||row.snippet||row.direction||"")}</p><small>{date(row.created_at||row.collected_at)}</small></div></article>)}{!rows.length&&<p>Aucun élément enregistré.</p>}</div>}
function ReviewPanel({leadId}:{leadId:string}){const[data,setData]=useState<Row|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function load(){setBusy(true);setError("");try{const response=await fetch(`/api/leads/${encodeURIComponent(leadId)}/reviews`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Avis indisponibles.");setData(payload);}catch(cause){setError(cause instanceof Error?cause.message:"Avis indisponibles.");}finally{setBusy(false);}}const reviews=Array.isArray(data?.reviews)?data.reviews as Row[]:[];return <div className="review-insights"><p>Lecture ciblée : un établissement, cinq avis maximum. Seuls les agrégats et thèmes sont conservés 24 h.</p><button onClick={()=>void load()} disabled={busy}>{busy?"Lecture…":"Analyser au plus 5 avis"}</button>{error&&<p className="search-error">{error}</p>}{data&&<><Fact label="Attribution" value={data.attribution}/><Fact label="Coût de cette lecture" value={data.cached?"0 USD (cache)":"non calculé — aucun appel automatique"}/><Fact label="Synthèse" value={(data.insight as Row|undefined)?.summary}/>{reviews.map((review,index)=><blockquote key={index}><strong>{String(review.rating||0)}/5</strong><p>{String(review.text||"")}</p><small>{String(review.author||"Auteur Google")}</small></blockquote>)}</>}</div>}
function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join("")||"?";}function date(value:unknown){if(!value)return"Non renseignée";const parsed=new Date(String(value));return Number.isNaN(parsed.getTime())?String(value):parsed.toLocaleString("fr-BE");}function format(value:unknown){if(value==null)return null;if(Array.isArray(value))return value.map(item=>typeof item==="object"?JSON.stringify(item):String(item)).join(" · ");if(typeof value==="object")return Object.entries(value as Row).map(([key,item])=>`${key}: ${String(item)}`).join(" · ");return String(value);}function slug(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-");}function temperature(value:string){return({chaud:"Chaud",tiede:"Tiède",froid:"Froid",non_contacte:"Non contacté"} as Record<string,string>)[value]||"Non contacté";}function stage(value:string){return({new:"Nouveau",to_qualify:"À qualifier",contacted:"Contacté",replied:"En discussion",meeting:"Rendez-vous",negotiation:"Négociation",won:"Gagné",lost:"Perdu"} as Record<string,string>)[value]||value||"Nouveau";}
