"use client";

import { FormEvent, useState } from "react";
import { Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";

type Duplicate = { id:string; company_name?:string; email?:string; phone?:string; legal_entity?:string };

export default function ManualLeadDialog({lexiconOnly=false}:{lexiconOnly?:boolean}) {
  const router=useRouter(); const[open,setOpen]=useState(false); const[busy,setBusy]=useState(false); const[error,setError]=useState(""); const[duplicates,setDuplicates]=useState<Duplicate[]>([]);
  async function submit(input:FormEvent<HTMLFormElement>|HTMLFormElement,confirmDuplicate=false){const formElement=input instanceof HTMLFormElement?input:input.currentTarget;if(!(input instanceof HTMLFormElement))input.preventDefault();setBusy(true);setError("");const form=new FormData(formElement);const body=Object.fromEntries(form.entries());if(confirmDuplicate)Object.assign(body,{confirmDuplicate:true});try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(response.status===409){setDuplicates(payload.duplicates||[]);setError("Doublon potentiel : ouvrez la fiche existante ou confirmez la création.");return;}if(!response.ok)throw new Error(payload.error||"Création impossible.");setOpen(false);router.push(`/leads/${encodeURIComponent(payload.item.id)}`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Création impossible.");}finally{setBusy(false);}}
  return <><button type="button" className="primary-cta manual-lead-open" onClick={()=>setOpen(true)}><Plus size={16}/>Ajouter un lead</button>{open&&<div className="modal-backdrop" role="presentation"><section className="manual-lead-dialog" role="dialog" aria-modal="true" aria-labelledby="manual-lead-title"><header><div><h2 id="manual-lead-title">Ajouter un lead manuellement</h2><p>Les doublons sont contrôlés avant la création.</p></div><button aria-label="Fermer" onClick={()=>setOpen(false)}><X size={18}/></button></header><form onSubmit={event=>void submit(event)}><label>Workspace<select name="workspace" defaultValue={lexiconOnly?"lexicon":"net-ai"} disabled={lexiconOnly}><option value="lexicon">Lexicon</option>{!lexiconOnly&&<><option value="pluq">Pluq</option><option value="profitflow">Profitflow</option><option value="net-ai">Net.AI</option></>}</select></label><label>Entreprise *<input name="company" required/></label><label>Personne<input name="contactName"/></label><label>Fonction<input name="title"/></label><label>Email<input name="email" type="email"/></label><label>Téléphone<input name="phone" type="tel"/></label><label>Site<input name="website" type="url"/></label><label>LinkedIn<input name="linkedinUrl" type="url"/></label><label>Adresse<input name="address"/></label><label>Secteur<input name="industry"/></label><label>Personne morale<input name="legalEntity"/></label><label>Bureau concerné<input name="officeScope"/></label><label>Valeur min. HT<input name="valueMin" type="number" min="0"/></label><label>Valeur max. HT<input name="valueMax" type="number" min="0"/></label><label>Consentement<select name="consentStatus"><option value="unknown">À confirmer</option><option value="legitimate_interest">Intérêt légitime documenté</option><option value="consented">Consentement</option><option value="opposed">Opposition</option></select></label><label>Source<input name="source" defaultValue="Saisie manuelle"/></label><label className="full">Notes<textarea name="notes"/></label>{error&&<p className="search-error full" role="alert">{error}</p>}{duplicates.length>0&&<div className="duplicate-list full">{duplicates.map(item=><a key={item.id} href={`/leads/${encodeURIComponent(item.id)}`}><strong>{item.company_name||"Lead existant"}</strong><span>{item.email||item.phone||item.legal_entity||"Coordonnées à vérifier"}</span></a>)}</div>}<footer className="full"><button type="button" onClick={()=>setOpen(false)}>Annuler</button>{duplicates.length>0&&<button type="submit" name="confirmDuplicate" value="true" onClick={event=>{event.preventDefault();void submit(event.currentTarget.form as unknown as FormEvent<HTMLFormElement>,true)}}>Créer malgré tout</button>}<button className="primary-cta" disabled={busy} type="submit">{busy?"Création…":"Créer le lead"}</button></footer></form></section></div>}</>;
}
