import { getAuthorizedChatGPTUser } from "@/app/chatgpt-auth";
import { supabaseRest } from "@/lib/email-connections";
import { canAccessWorkspace, normalizeWorkspace, WORKSPACE_CONFIGS } from "@/lib/workspaces";

export async function getLeadDetail(_request:Request,{params}:{params:Promise<{id:string}>}){
  const user=await getAuthorizedChatGPTUser();if(!user)return Response.json({error:"Accès non autorisé."},{status:401});const id=(await params).id.trim();
  const response=await supabaseRest(`leads?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);const rows=response.ok?await response.json() as Array<Record<string,unknown>>:[];if(!rows[0])return Response.json({error:"Lead introuvable."},{status:404});const lead=rows[0];
  const workspaceResponse=await supabaseRest(`workspaces?id=eq.${encodeURIComponent(String(lead.workspace_id||""))}&select=id,slug,name&limit=1`);const workspaceRows=workspaceResponse.ok?await workspaceResponse.json() as Array<{id:string;slug:string;name?:string}>:[];const workspace=workspaceRows[0];if(!workspace||!canAccessWorkspace(user,normalizeWorkspace(workspace.slug)))return Response.json({error:"Lead introuvable."},{status:404});
  const [contacts,evidence,sources,activities,messages,searchRuns,jobs,drafts,sequences,tasks]=await Promise.all([
    get(`lead_contacts?lead_id=eq.${encodeURIComponent(id)}&select=*&order=is_primary.desc,confidence_score.desc`),get(`evidence?lead_id=eq.${encodeURIComponent(id)}&select=*&order=collected_at.desc&limit=100`),get(`enrichment_sources?lead_id=eq.${encodeURIComponent(id)}&select=*&order=collected_at.desc&limit=50`),get(`lead_activities?lead_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=100`),get(`email_messages?lead_id=eq.${encodeURIComponent(id)}&select=*,email_attachments(*)&order=sent_at.asc&limit=200`),lead.search_run_id?get(`search_runs?id=eq.${encodeURIComponent(String(lead.search_run_id))}&select=*&limit=1`):Promise.resolve([]),get(`enrichment_runs?lead_id=eq.${encodeURIComponent(id)}&select=id,status,progress,attempts,result,error_message,created_at,completed_at,finished_at&order=created_at.desc&limit=10`),get(`email_drafts?lead_id=eq.${encodeURIComponent(id)}&select=*&order=updated_at.desc`),get(`email_sequences?lead_id=eq.${encodeURIComponent(id)}&select=*,email_sequence_steps(*,email_sequence_step_versions(*))&order=created_at.desc`),get(`crm_tasks?lead_id=eq.${encodeURIComponent(id)}&select=*&order=due_at.asc`),
  ]);
  return Response.json({item:{...normalizeLead(lead),workspace:{slug:workspace.slug,label:WORKSPACE_CONFIGS[normalizeWorkspace(workspace.slug)].label},contacts,evidence,sources,activities,messages,drafts,sequences,tasks,searchRun:searchRuns[0]||null,enrichmentJobs:jobs}});
}
async function get(path:string){const response=await supabaseRest(path);return response.ok?response.json() as Promise<Array<Record<string,unknown>>>:[];}
function normalizeLead(row:Record<string,unknown>){const raw=row.raw_data&&typeof row.raw_data==="object"?redact(row.raw_data):{};return{id:row.id,externalId:row.external_id,workspaceId:row.workspace_id,searchRunId:row.search_run_id,company:row.legal_name||row.company_name||"Entreprise inconnue",legalName:row.legal_name,description:row.description||value(raw,"description"),activity:row.industry,sector:row.sector||row.industry,category:row.category||row.industry,website:row.website,domain:row.domain,email:row.email,phone:row.phone,address:row.address,city:row.city,region:row.region,country:row.country_code,latitude:row.latitude||value(raw,"latitude")||value(raw,"lat"),longitude:row.longitude||value(raw,"longitude")||value(raw,"lng"),googlePlaceId:row.google_place_id||value(raw,"placeId"),googleMapsUrl:row.google_maps_url||value(raw,"url"),googleBusinessUrl:row.google_business_url,rating:row.rating||value(raw,"totalScore"),reviewCount:row.review_count||value(raw,"reviewsCount"),openingHours:row.opening_hours,photoUrl:row.photo_url||firstImage(raw),logoUrl:row.logo_url,socialLinks:row.social_links,companySize:row.company_size,employeeCount:row.employee_count,foundedYear:row.founded_year,linkedinUrl:row.linkedin_url,score:Number(row.fit_score||row.score||0),priorityScore:Number(row.priority_score||0),confidence:Number(row.data_confidence||row.confidence||0),scoreBreakdown:row.score_breakdown||{},scoreModelVersion:row.score_model_version,temperature:row.temperature,pipelineStage:row.pipeline_stage||row.deal_status,status:row.status,opportunityValue:Number(row.opportunity_value||0),nextAction:row.next_action,nextActionAt:row.next_action_at,lastInteractionAt:row.last_interaction_at,lastEnrichedAt:row.last_enriched_at,createdAt:row.created_at,updatedAt:row.updated_at,rawData:raw};}
function value(raw:unknown,key:string){return raw&&typeof raw==="object"?(raw as Record<string,unknown>)[key]:null;}function firstImage(raw:unknown){const images=value(raw,"imageUrls");return Array.isArray(images)&&typeof images[0]==="string"?images[0]:value(raw,"imageUrl");}
function redact(value:unknown):unknown{if(Array.isArray(value))return value.map(redact);if(!value||typeof value!=="object")return value;return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>!/(token|secret|password|api[_-]?key|service[_-]?role)/i.test(key)).map(([key,item])=>[key,redact(item)]));}
