import { getAuthorizedChatGPTUser } from "@/app/chatgpt-auth";
import { supabaseRest } from "@/lib/email-connections";
import { canAccessWorkspace, normalizeWorkspace, WORKSPACE_CONFIGS } from "@/lib/workspaces";

const stageValues = new Set(["new","to_qualify","qualified","contacted","replied","meeting","negotiation","won","lost","blocked"]);
const temperatureValues = new Set(["non_contacte","froid","tiede","chaud"]);
const sortMap:Record<string,string>={score:"fit_score.desc,updated_at.desc",priority:"priority_score.desc,fit_score.desc",created:"created_at.desc",interaction:"last_interaction_at.desc.nullslast",nextAction:"next_action_at.asc.nullslast",company:"company_name.asc"};

export async function listLeads(request:Request) {
  const user=await getAuthorizedChatGPTUser(); if(!user)return Response.json({error:"Accès non autorisé."},{status:401});
  const url=new URL(request.url), page=Math.max(1,Number(url.searchParams.get("page")||1)), pageSize=Math.min(100,Math.max(1,Number(url.searchParams.get("pageSize")||50)));
  const workspaceRows=await readJson<Array<{id:string;slug:string;name?:string}>>(await supabaseRest("workspaces?select=id,slug,name&order=name.asc"));
  const authorized=workspaceRows.filter(row=>canAccessWorkspace(user,normalizeWorkspace(row.slug))); const requested=url.searchParams.get("workspace");
  const selected=requested?authorized.filter(row=>row.slug===normalizeWorkspace(requested)):authorized;
  if(requested&&!selected.length)return Response.json({error:"Espace non autorisé."},{status:403}); if(!selected.length)return Response.json({items:[],page,pageCount:1,total:0,counts:{},pipelineValue:0});
  const ids=selected.map(row=>row.id); const params=new URLSearchParams({select:"id,external_id,workspace_id,search_run_id,company_name,legal_name,description,industry,sector,category,address,city,region,country_code,phone,email,website,domain,linkedin_url,photo_url,logo_url,latitude,longitude,google_place_id,google_maps_url,rating,review_count,score,fit_score,priority_score,data_confidence,score_breakdown,temperature,pipeline_stage,status,deal_status,opportunity_value,next_action,next_action_at,last_interaction_at,last_enriched_at,created_at,updated_at",workspace_id:`in.(${ids.join(",")})`,order:sortMap[url.searchParams.get("sort")||""]||sortMap.score,limit:String(pageSize),offset:String((page-1)*pageSize)});
  applyFilters(params,url.searchParams);
  const response=await supabaseRest(`leads?${params}`,{headers:{Prefer:"count=exact"}}); if(!response.ok)return Response.json({error:`Lecture des leads impossible (${response.status}).`},{status:503});
  const rows=await response.json() as Array<Record<string,unknown>>, range=response.headers.get("content-range"), total=range&&/\/(\d+)$/.exec(range)?.[1]?Number(/\/(\d+)$/.exec(range)![1]):rows.length;
  const summaryParams=new URLSearchParams({select:"workspace_id,temperature,pipeline_stage,deal_status,status,fit_score,opportunity_value,next_action_at,email,phone,linkedin_url,photo_url,last_enriched_at",workspace_id:`in.(${authorized.map(row=>row.id).join(",")})`,limit:"5000"});
  const summary=await readJson<Array<Record<string,unknown>>>(await supabaseRest(`leads?${summaryParams}`)); const now=Date.now(); const counts:Record<string,number>={authorized:summary.length};
  for(const lead of summary){const slug=workspaceRows.find(workspace=>workspace.id===lead.workspace_id)?.slug||"net-ai";counts[`workspace_${slug}`]=(counts[`workspace_${slug}`]||0)+1;if(lead.temperature==="chaud")counts.hot=(counts.hot||0)+1;if(!lead.last_enriched_at||lead.status==="pending")counts.pending=(counts.pending||0)+1;if(lead.next_action_at&&new Date(String(lead.next_action_at)).getTime()<now)counts.overdue=(counts.overdue||0)+1;const stage=String(lead.pipeline_stage||lead.deal_status||"");if(stage)counts[stage]=(counts[stage]||0)+1;}
  const pipelineValue=summary.filter(item=>!["won","lost"].includes(String(item.pipeline_stage||item.deal_status))).reduce((sum,item)=>sum+Number(item.opportunity_value||0),0);
  return Response.json({items:rows.map(row=>normalize(row,workspaceRows)),page,pageSize,total,pageCount:Math.max(1,Math.ceil(total/pageSize)),counts,pipelineValue});
}

function applyFilters(params:URLSearchParams,query:URLSearchParams){const text=query.get("q")?.trim();if(text)params.set("or",`(company_name.ilike.*${safe(text)}*,legal_name.ilike.*${safe(text)}*,email.ilike.*${safe(text)}*,address.ilike.*${safe(text)}*,city.ilike.*${safe(text)}*)`);const stage=query.get("status");if(stage&&stageValues.has(stage))params.set("pipeline_stage",`eq.${stage}`);const temperature=query.get("temperature");if(temperature&&temperatureValues.has(temperature))params.set("temperature",`eq.${temperature}`);for(const [key,column] of [["country","country_code"],["region","region"],["city","city"],["sector","sector"],["category","category"]] as const){const value=query.get(key)?.trim();if(value)params.set(column,`ilike.*${safe(value)}*`);}const score=Number(query.get("scoreMin"));if(Number.isFinite(score)&&score>0)params.set("fit_score",`gte.${Math.min(100,score)}`);for(const [key,column] of [["hasEmail","email"],["hasPhone","phone"],["hasLinkedin","linkedin_url"],["hasPhoto","photo_url"]] as const){const value=query.get(key);if(value==="true")params.set(column,"not.is.null");if(value==="false")params.set(column,"is.null");}if(query.get("enrichment")==="pending")params.set("last_enriched_at","is.null");if(query.get("nextAction")==="overdue")params.set("next_action_at",`lt.${new Date().toISOString()}`);if(query.get("createdFrom"))params.set("created_at",`gte.${query.get("createdFrom")}T00:00:00Z`);if(query.get("lastInteractionFrom"))params.set("last_interaction_at",`gte.${query.get("lastInteractionFrom")}T00:00:00Z`);if(query.get("nextActionBefore"))params.set("next_action_at",`lte.${query.get("nextActionBefore")}T23:59:59Z`);if(query.get("campaign"))params.set("search_run_id",`eq.${safe(query.get("campaign")!)}`);}
function normalize(row:Record<string,unknown>,workspaces:Array<{id:string;slug:string;name?:string}>){const workspace=workspaces.find(item=>item.id===row.workspace_id);return{id:row.id,externalId:row.external_id,company:row.legal_name||row.company_name||"Entreprise inconnue",category:row.category||row.industry,sector:row.sector||row.industry,location:row.address,city:row.city,region:row.region,country:row.country_code,email:row.email,phone:row.phone,website:row.website,linkedinUrl:row.linkedin_url,photoUrl:row.photo_url,logoUrl:row.logo_url,score:Number(row.fit_score||row.score||0),priorityScore:Number(row.priority_score||0),confidence:Number(row.data_confidence||0),temperature:row.temperature,pipelineStage:row.pipeline_stage,dealStatus:row.deal_status,opportunityValue:Number(row.opportunity_value||0),nextAction:row.next_action,nextActionAt:row.next_action_at,lastInteractionAt:row.last_interaction_at,enrichmentStatus:row.status,searchRunId:row.search_run_id,createdAt:row.created_at,workspace:{slug:workspace?.slug||"net-ai",label:WORKSPACE_CONFIGS[normalizeWorkspace(workspace?.slug)].label}};}
async function readJson<T>(response:Response):Promise<T>{if(!response.ok)return [] as T;return response.json() as Promise<T>;}
function safe(value:string){return value.replace(/[(),.*]/g," ").trim().slice(0,120);}
